language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'

install:
    - composer install --no-interaction

cache:
    directories:
        - "$HOME/.composer/cache"

script:
    - ./vendor/bin/phpstan analyze --configuration=phpstan.neon --level=max --no-interaction --no-progress src/ tests/
    - ./vendor/bin/phpunit
